import cv2

img = cv2.imread("/Users/apple/Downloads/PRO-C116-project-image-main-main/solar-system.jpg")

cv2.putText(img,
            "Sun",
            (20,300),
            fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,
            fontScale=1,
            color=(255,255,255)
            )
cv2.putText(img,
            "Mercury",
            (100,250),
            fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,
            fontScale=1,
            color=(255,255,255)
            )
cv2.putText(img,
            "Venus",
            (183,300),
            fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,
            fontScale=1,
            color=(255,255,255)
            )
cv2.putText(img,
            "Earth",
            (285,300),
            fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,
            fontScale=1,
            color=(255,255,255)
            )
cv2.putText(img,
            "Mars",
            (375,300),
            fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,
            fontScale=1,
            color=(255,255,255)
            )
cv2.putText(img,
            "Jupiter",
            (550,400),
            fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,
            fontScale=1,
            color=(255,255,255)
            )
cv2.putText(img,
            "Saturn",
            (750,300),
            fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,
            fontScale=1,
            color=(255,255,255)
            )
cv2.putText(img,
            "Uranus",
            (950,300),
            fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,
            fontScale=1,
            color=(255,255,255)
            )
cv2.putText(img,
            "Neptune",
            (1100,300),
            fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,
            fontScale=1,
            color=(255,255,255)
            )
            
cv2.imshow("output",img)
cv2.imwrite("/Users/apple/Downloads/PRO-C116-project-image-main-main/Solar-systemwithname.jpg",img)
cv2.waitKey(0)